### ISSUE TITLE
face-data-server executable fail after calibration

### ISSUE THREAD

**Issue by Cj-bc** [Cj-bc/Face-data-server#47]
```
<X_X>:Face-data-server$ ./face-data-server 
=========== Face calibration ===========
Please face front and press enter:
got your face... wait for a second...
Traceback (most recent call last):
  File "main.py", line 114, in <module>
    main()
  File "main.py", line 63, in main
    calib, initialRatio = faceCalibration(cap)
  File "/Users/me/.ghq/github.com/Cj-bc/Face-data-server/FaceDataServer/faceDetection.py", line 31, in faceCalibration
    face, ratio = Face.fromDPointsWithRatio(facemark(frame))
  File "/Users/me/.ghq/github.com/Cj-bc/Face-data-server/FaceDataServer/faceDetection.py", line 71, in facemark
    absolute_coord = _sortDpoints(_getBiggestFace(wholeFace))
  File "/Users/me/.ghq/github.com/Cj-bc/Face-data-server/FaceDataServer/faceDetection.py", line 113, in _getBiggestFace
    faces, dlib.dpoints(194))
  File "/Users/me/.ghq/github.com/Cj-bc/Face-data-server/FaceDataServer/faceDetection.py", line 112, in <lambda>
    return reduce(lambda p, q: p if ln(p) > ln(q) else q,
  File "/Users/me/.ghq/github.com/Cj-bc/Face-data-server/FaceDataServer/faceDetection.py", line 110, in ln
    return abs((p[40] - p[0]).x)
IndexError
```

**Comment by Cj-bc** [comment]
This was because of the `map object` of python.
It's 'lazy' object. It means It wont evaluated till it's needed.
As `_points2dpoints` used this, It didn't evaluate `ret.append`.
https://github.com/Cj-bc/Face-data-server/blob/78d19841f081c819c3f550b193b40ff39823298a/FaceDataServer/faceDetection.py#L208

I don't know why this wasn't issue before, but current issue is that.

**Comment by Cj-bc** [comment]
It's already merged on develop branch.
